export const UI = {
  app: document.querySelector(".app"),
  alertBox: document.querySelector(".alertBox"),
  disconnectButton: document.querySelector(".disconnectButton"),
  formButton: document.querySelector(".formButton"),
  form: {
    dateInput: document.querySelector(".dateInput"),
    cityInput: document.querySelector(".cityInput"),
    depNumInput: document.querySelector(".depNumInput"),
    placeInput: document.querySelector(".placeInput"),
    ticketsLinkInput: document.querySelector(".ticketsLinkInput"),
  },
  updateForm: {
    dateUpdateInput: document.querySelector(".dateUpdateInput"),
    cityUpdateInput: document.querySelector(".cityUpdateInput"),
    depNumUpdateInput: document.querySelector(".depNumUpdateInput"),
    placeUpdateInput: document.querySelector(".placeUpdateInput"),
    ticketsLinkUpdateInput: document.querySelector(".ticketsLinkUpdateInput"),
  },
  modal: {
    modalBackground: document.querySelector(".modalBackground"),
    modalContainer: document.querySelector(".modalContainer"),
    updateModal: document.querySelector(".updateModal"),
    deleteModal: document.querySelector(".deleteModal"),
    modalTitle: document.querySelector(".modalTitle"),
    yesButton: document.querySelector(".yesButton"),
    noButton: document.querySelector(".noButton"),
  },
  columns: {
    col1: document.getElementsByClassName("col1"),
    col2: document.getElementsByClassName("col2"),
    col3: document.getElementsByClassName("col3"),
    col4: document.getElementsByClassName("col4"),
    col5: document.getElementsByClassName("col5"),
    col6: document.getElementsByClassName("col6"),
  },
};
